### ISSUE TITLE
Question/Protobuf definitions

### ISSUE THREAD

**Issue by cainthebest** [G-PORTAL/gpcloud-go#6]
Where can I find the protobuf definitions for gportal gRPC, I see in the archived repo there are definitions there but are they correct and if not where would I find the latest definitions. Thanks

**Comment by f0086** [comment]
The protobuf definitions can be found here: https://buf.build/gportal/gportal-cloud/assets/main
For a quick reference, you can use the generated docs: https://buf.build/gportal/gportal-cloud
We are working on improving the documentation right now.

**Comment by cainthebest** [comment]
@f0086 amazing thank you, with these changes will there be changes to the rest api or is the main focus in gRPC

**Comment by f0086** [comment]
We are focusing on the gRPC API, this is the source of truth (the protobuf-files). The REST API is a "byproduct" from the [grpc-gateway](https://grpc-ecosystem.github.io/grpc-gateway/), which will make the API accessible over REST. Because it's source is also the protobuf definitions, the REST API will always in line with the gRPC API. If the protobuf definitions change, both (REST and gRPC API) will change.

**Comment by cainthebest** [comment]
Is it possible to obtain the PB files from BSR remotely? Currently, only the definitions for Go and JS/TS clients are accessible through buf, and the assets on the BSR require authentication to access. If remote access to the PB files is not possible, could a mirror repository be created on Github or an alternative method be used for remote access?

**Comment by f0086** [comment]
Sorry for the long delay on this.
You can dump the whole protobuf files with the ```buf export``` sub command like this (make sure you installed the [buf](https://docs.buf.build/reference/cli/buf) tool):

```
$ buf export buf.build/gportal/gportal-cloud -o .
```

I've updated the ```README``` accordingly.
Alternative, you can pull it from here: https://github.com/G-PORTAL/gpcloud-proto

**Comment by cainthebest** [comment]
Thanks all, appreciate it
